
name: "Deploy app to k8s cluster"
on:
  workflow_dispatch:
  push:
    # run on push to master
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build the stack
      run: docker-compose up -d

    - name: Test frontend
      run: |
        sleep 10
        if curl -s localhost:8080 | grep 'Azure Voting App'
        then
            echo "Test passed!"
        else
            echo "Test failed!"
            exit 1
        fi  

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to AKS
      run: |
        az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}
        az aks get-credentials --resource-group RSG-DEV-REXP-CU --name dev-cluster
        kubectl get namespace -oname | grep "namespace/vote-app" \
            || kubectl create namespace vote-app
        kubectl apply -f kubernetes -n vote-app
        

    
